<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="listener.Listener"/>
  </listeners>
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="exceptionTests.StringOperation">
        <methods>
          <include name="shouldCompareCaseSensitiveString4"/>
          <include name="shouldCompareCaseSensitiveString2"/>
          <include name="testStringContains"/>
          <include name="testStringSubstring"/>
          <include name="shouldCompareCaseSensitiveString3"/>
          <include name="testStringConcatenation"/>
          <include name="shouldCompareCaseSensitiveString"/>
          <include name="testStringUpperCase"/>
          <include name="testStringLength"/>
          <include name="testStringLowerCase"/>
        </methods>
      </class> <!-- exceptionTests.StringOperation -->
      <class name="exceptionTests.ExceptionTest">
        <methods>
          <include name="testIndexOutOfBoundsException"/>
          <include name="testArithmeticException2"/>
          <include name="testArithmeticException"/>
          <include name="testNullPointerException"/>
          <include name="testMultipleExceptions"/>
        </methods>
      </class> <!-- exceptionTests.ExceptionTest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
